### ISSUE TITLE
xbuild and msbuild error

### ISSUE THREAD

**Issue by kokoye2007** [mcq8/BeID#1]
/EID/BeID/SampleEidUsage/SampleEidUsage.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets (ResolveProjectReferences target) ->
/EID/BeID/EidReader/EidReader.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets (ResolveAssemblyReferences target) ->

	/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : Reference 'System.ServiceProcess' not resolved
	/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : Reference 'System.Windows.Forms' not resolved

	 2 Warning(s)
	 0 Error(s)

**Comment by mcq8** [comment]
Are you using a specific build environment?
When I build it using the mono:6 docker image, I don't get those warnings.

**Comment by kokoye2007** [comment]
> Are you using a specific build environment?
> When I build it using the mono:6 docker image, I don't get those warnings.

I will test with docker and report to you.

**Comment by kokoye2007** [comment]
Its work 
-  mono:6 docker image
Thanks
